// Changelog powering the in-app "What's new" panel for MANAGER itself.
// (Per-project changelogs live in the Store `releases` table — this is the
// app's own release history.) Newest first.
//
// The hourly self-improvement loop appends a new entry at the TOP for each
// user-visible change (bump `v`, short `title`, optional `kind`, 1–4 `items`).
// Leave `ts` as an EMPTY string on the new entry — the workflow stamps it with
// the real commit time so timestamps are never fabricated. `ts` is ISO-8601
// UTC; the panel formats it to Central Time (shown as CT).
export const CHANGELOG = [
  {
    v: 92,
    title: 'Landing backdrop settles into Manager’s own blue',
    kind: 'polish',
    ts: '2026-07-22T21:24:49.291Z',
    items: [
      'The drifting aurora on the landing page now stays in Manager’s cyan-and-sky brand blues instead of straying into indigo and violet, so the front door matches the app’s mark.',
    ],
  },
  {
    v: 91,
    title: 'The Manager mark now wears its brand color everywhere',
    kind: 'polish',
    ts: '2026-07-22T20:56:52.834Z',
    items: [
      'The rail brand tile and the app-switcher tiles now use Manager’s own brand gradient — the same vivid color you see on its polecat.live launcher tile and landing page, so the mark reads identically everywhere.',
      'Built on Polecat Shell v0.5.4.',
    ],
  },
  {
    v: 90,
    title: 'The app rail now wears Manager’s own mark',
    kind: 'polish',
    ts: '2026-07-22T19:53:02.087Z',
    items: [
      'The rail brand is now Manager’s glyph — the same mark you see on its polecat.live launcher tile and its landing-page header — so the app reads as one identity everywhere.',
      'A faint “polecat.live” link sits just under the name in the rail: a quiet way back to the suite.',
      'Built on Polecat Shell v0.5.3.',
    ],
  },
  {
    v: 89,
    title: 'Milestone suggestions moved onto the timeline — and got rare',
    kind: 'polish',
    ts: '2026-07-22T19:47:52.519Z',
    items: [
      'The “Recommended release point” banner is gone. When a release genuinely stands out as a natural stable point, Manager now marks it right on the What’s-new timeline with a quiet “Suggested” badge (tooltip explains why) — click it to accept, × to dismiss.',
      'It’s deliberately rare now: at most one suggestion per project, often none, and it no longer drops to a weaker pick when you dismiss one — so busy projects like Analytics stop showing an endless stream of things to accept or dismiss.',
    ],
  },
  {
    v: 88,
    title: 'The Projects list no longer flashes while it checks for updates',
    kind: 'fix',
    ts: '2026-07-22T19:36:31.428Z',
    items: [
      'The new background “check for updates” on the Projects library synced each project one after another, and every one repainted the whole list — so landing on the page flashed several times. The refresh now batches all its writes and updates the list in a single repaint, with a small “Checking for updates…” note while it runs.',
    ],
  },
  {
    v: 87,
    title: 'Fix: Fleet Ops was burning through the GitHub rate limit',
    kind: 'fix',
    ts: '2026-07-22T18:38:05.620Z',
    items: [
      'Expanding a steward run in the Steward log re-fetched its whole detail — journal, job log, and a fleet-wide Search for what it produced — on every 30-second live poll. Since a completed run never changes, that was pure waste, and the Search API has a much tighter per-minute limit, so a couple of expanded runs left open could drain the budget and 403 every panel (including the Focus roster, even with a token connected). A completed run’s detail is now fetched once and reused; only still-running runs keep refreshing.',
      'When a rate limit does hit, the message now tells you the actual clock time it resets (from GitHub’s own headers) instead of a vague “within the hour” — and it no longer suggests connecting a token when you already have one connected.',
    ],
  },
  {
    v: 86,
    title: 'Projects checks for new releases on its own — and flags what’s new',
    kind: 'feature',
    ts: '2026-07-22T18:24:49.788Z',
    items: [
      'Opening the Projects library now quietly pulls fresh changelogs for every connected project in the background, so you don’t have to hit “Sync all” each visit (throttled so rapid navigation doesn’t hammer anything, and silent — an unreachable source just doesn’t flag anything).',
      'When a background check actually finds new releases for a project, its row gets a transient NEW badge. It clears the moment you open that project, and fades on its own after about ten days if you never do — so NEW always means “genuinely new since you last looked”, never a permanent sticker.',
    ],
  },
  {
    v: 85,
    title: 'The marketing carousel’s caption no longer dims the screenshot',
    kind: 'polish',
    ts: '2026-07-22T18:13:44.380Z',
    items: [
      'The caption gradient over the hero screenshots on the public site was heavy enough to shade a big chunk of the image, making the app itself hard to read. It’s now a lighter, shorter scrim anchored at the very bottom, with a soft text-shadow keeping the caption legible — so the screenshot reads clearly and the words still pop.',
    ],
  },
  {
    v: 84,
    title: 'The recommended release point can now be dismissed',
    kind: 'fix',
    ts: '2026-07-22T18:06:38.088Z',
    items: [
      'The “Recommended release point” nudge on a project page had no way to go away — even after you marked the suggested release as a milestone, it kept showing. It now has a dismiss (×), and both dismissing it and marking it as a milestone clear it for good.',
      'A dismissal sticks to that specific version, so the same suggestion won’t reappear — but if the project later settles at a new stable point, a fresh recommendation still surfaces.',
    ],
  },
  {
    v: 83,
    title: 'Fix: Fleet Ops now loads the roster once your token connects',
    kind: 'fix',
    ts: '2026-07-22T17:59:54.001Z',
    items: [
      'If the Focus roster opened before your vault token was ready — for example while the credential was still locked — it loaded anonymously, hit GitHub’s low unauthenticated rate limit, and got stuck on a “403 — connect a token” note even though the header above it said “Connected”. It now refetches the roster and the other Fleet Ops cards the moment the connection proves good (or you switch tokens), so authenticated data replaces the anonymous error automatically.',
    ],
  },
  {
    v: 82,
    title: 'The landing page now wears the shared fleet header & footer',
    kind: 'polish',
    ts: '2026-07-22T17:57:50.862Z',
    items: [
      'Manager’s front door adopts the suite-wide header and footer, so it matches every Polecat app — the same brand tile, a consistent “Polecat” link back to the suite, and the standard footer.',
      'Picked up Polecat Shell v0.5.1 (the shared site-chrome plus the ~44px mobile touch targets).',
    ],
  },
  {
    v: 81,
    title: 'Fleet Ops: dial how many slices an app runs per fire',
    kind: 'feature',
    ts: '2026-07-22T17:03:13.676Z',
    items: [
      'Each app lane in the Focus roster now has a ×N control next to its cadence. Leave it at ×1 for the usual one-unit-of-work-per-run, or push a lane you want to move faster up to ×5 — that many independent improve runs fire each time the lane is due, each a full unit with its own pull request and smoke gate, run back-to-back so the app never overlaps itself.',
      'A boosted lane lights up in the roster and shows its multiplier in the Coming-up list, so it’s obvious at a glance which app is being pushed harder. It’s just a roster setting (focus.json), so it takes effect on the next hourly tick and needs no workflow changes.',
    ],
  },
  {
    v: 80,
    title: 'Fix: Fleet Ops tells you when a private repo will never load without a token',
    kind: 'fix',
    ts: '2026-07-22T17:12:18.811Z',
    items: [
      'The "Open steward work across the fleet" summary lumped every unreachable repo into one "rate limit or private — connect a token" guess. A private repo (like Solution Engineering) permanently 404s to the unauthenticated GitHub API — no amount of waiting fixes it, unlike a 403 rate limit, which clears within the hour on its own. The summary now tells the two apart and names the private repo directly.',
    ],
  },
  {
    v: 79,
    title: 'Polish: stat cards get a pointer cursor on hover',
    kind: 'polish',
    ts: '2026-07-22T17:06:05.240Z',
    items: [
      'The Dashboard and Releases stat tiles (Live now, Fleet health, Shipped·7d, etc.) have been clickable and keyboard-navigable since v74, but the mouse cursor never changed on hover — a UX-sweep finding. They now show a pointer, matching every other clickable card in the app.',
    ],
  },
  {
    v: 78,
    title: 'Polish: thumb-sized tap targets on mobile',
    kind: 'polish',
    ts: '2026-07-22T16:57:10.995Z',
    items: [
      'Filter chips, toggle switches, Fleet Ops icon buttons, and most secondary buttons (Settings, Credentials, Activity, the invite gate) were well under the ~44px mobile touch-target floor — a UX-sweep finding carried unaddressed across three sweeps. They now meet it on phone-width screens, both themes, with no change to desktop.',
    ],
  },
  {
    v: 77,
    title: 'The blurry hero screenshots are finally, genuinely sharp',
    kind: 'fix',
    ts: '2026-07-22T16:47:55.783Z',
    items: [
      'The real cause of the soft carousel: Manager’s glassy rail and cards use a backdrop blur, which trips a browser bug where capturing the page at 2× (for crisp retina art) rasterizes the whole page at half resolution and scales it back up — so every screenshot came out uniformly fuzzy no matter the file size or cache tag.',
      'The screenshot generator now switches that backdrop blur off for the capture only (the live app is untouched — the panels look identical because they carry their own background), so the shots are now pin-sharp at full 2× resolution.',
    ],
  },
  {
    v: 76,
    title: 'Fix: the hero screenshots were showing a stale, blurry cached copy',
    kind: 'fix',
    ts: '2026-07-22T15:55:47.083Z',
    items: [
      'The new hi-res hero screenshots share the same filenames as the originals, so browsers (and the CDN) kept serving the first, lower-resolution copy — the carousel looked blurry even though the deployed images were sharp. The image URLs now carry a version tag so an updated screenshot is always fetched fresh.',
    ],
  },
  {
    v: 75,
    title: 'A brand-new public site — real screenshots, and it finally shows Fleet Ops',
    kind: 'feature',
    ts: '2026-07-22T14:23:02.568Z',
    items: [
      'The marketing site (manager.polecat.live) got a proper glow-up: the hero is now an auto-rotating carousel of real, freshly-captured app screenshots — the dashboard, Fleet Ops, the Steward log, the library, and the releases feed — instead of a faked-up mockup.',
      'The copy caught up with what Manager actually is now: driving the platform steward from Fleet Ops, reviewing what each run did in the Steward log, connecting a real database, and encrypting secrets at rest — none of which the old site mentioned.',
      'The screenshots regenerate from the live app at deploy time (a new .github/gen-shots.mjs), so the site can never drift from the real UI. A smoke check guards the carousel — real images, working dots, auto-advance.',
    ],
  },
  {
    v: 74,
    title: 'Dashboard and Releases stat tiles now link to their detail',
    kind: 'fix',
    ts: '2026-07-18T19:01:46.479Z',
    items: [
      'The Dashboard’s Projects/Live now/Shipped·7d/Feature runs/Fleet health cards and the Releases page’s Last 7 days/Last 30 days/All time/Most recent cards were plain non-interactive numbers. Each now opens the filtered view behind it — Live now and Fleet health jump to the library pre-filtered (Fleet health sorts worst-first, a new sort option), Shipped·7d and the range cards jump to Releases pre-scoped to that window, Feature runs opens the cadence log, and Most recent opens the project that shipped it.',
      'Also fixed a mobile layout regression: the project detail page’s two-column grid could force a wider-than-viewport layout at narrow widths (320px), causing horizontal overflow.',
    ],
  },
  {
    v: 73,
    title: 'Fleet Ops splits in two: the control room and the Steward log',
    kind: 'polish',
    ts: '2026-07-17T23:07:21.751Z',
    items: [
      'Fleet Ops was doing two jobs on one page. Now the rail has both: Fleet Ops is the control room — GitHub access, the schedule roster, and one-off runs — and a new Steward log section holds what has happened: the safety nets, expandable run reviews, and open steward work across the fleet. Each links to the other from its header.',
      'The dead space next to the roster became a “Coming up” card: the next ten scheduled runs across every lane and platform job, computed from the roster exactly as shown — including edits you haven’t committed yet, so you can preview a schedule change before committing it.',
    ],
  },
  {
    v: 72,
    title: 'Run reviews now tell you what happened, in the steward’s own words',
    kind: 'feature',
    ts: '2026-07-17T22:37:14.744Z',
    items: [
      'Expanding a steward run now leads with the run’s own summary — every steward job (improve runs, both sweeps, the janitor) now journals what it actually did when it finishes, and Manager shows that narrative first: which app it picked, what shipped, the PR it opened, the issues a sweep filed, what the janitor merged or parked.',
      'The CI process noise is gone from the review: the step-by-step list (checkout, install, cache…) is demoted to a one-line job summary, with individual steps shown only when something failed.',
      'Older runs from before the journal existed say so and keep the time-correlated view; “Full log on GitHub” remains for the raw console output.',
    ],
  },
  {
    v: 71,
    title: 'Steward runs are readable and openable on a phone',
    kind: 'fix',
    ts: '2026-07-17T22:29:44.034Z',
    items: [
      'On mobile, the Recent steward runs list squashed each run’s name down to a few letters and the details were effectively impossible to open. Now the run name owns its full line, the status and time wrap onto a second line beneath it, and the event label (workflow_dispatch/schedule) — pure noise on a small screen — is hidden.',
      'Tapping anywhere on a run’s name toggles its details too, not just the small chevron, and the chevron itself grew to a proper thumb-sized target. The safety-nets rows drop their descriptions on phones for the same breathing room.',
    ],
  },
  {
    v: 70,
    title: 'Review what every steward run actually did, in place',
    kind: 'feature',
    ts: '2026-07-17T15:16:11.015Z',
    items: [
      'Each row in Recent steward runs now expands (chevron) into an in-panel review: the run’s job and step log — every step with its pass/fail dot and duration — plus what the run produced: issues filed by a sweep, PRs opened by an improve run, PRs merged by the janitor, each linking straight to the item.',
      'Production is time-correlated (everything created fleet-wide during the run’s execution window) and labeled as such; a run that produced nothing says so plainly, and the full GitHub log is always one click away.',
      'Detail lookups ride the same request cache and degrade gracefully when rate-limited. Also fixed underneath: every GitHub call now carries an 8-second deadline, so a network that hangs connections (instead of refusing them) can no longer leave cards spinning on “Loading…” forever.',
    ],
  },
  {
    v: 69,
    title: 'Fleet Ops stops burning the anonymous GitHub budget',
    kind: 'fix',
    ts: '2026-07-16T22:15:41.782Z',
    items: [
      'Without a vault token, GitHub allows only ~60 API requests per hour per network — and Fleet Ops had grown hungry enough that a few page opens could drain it and 403 every card. Reads are now cached for 10 minutes when unauthenticated (25 seconds with a token, so live-follow stays live), and any write or manual refresh busts the cache.',
      'The expensive extras are token-gated: per-PR check dots and the background steward-signals sweep only run with a token connected, since they fan out across every repo.',
      'A rate limit now reads as what it is — an amber “resets within the hour; connect a vault token to raise limits” note instead of a red error. Nothing needs re-setup; anonymous mode heals on its own.',
    ],
  },
  {
    v: 68,
    title: 'The whole platform schedule in one place — sweeps, janitor, and fleet improve join the roster',
    kind: 'feature',
    ts: '2026-07-16T21:38:41.420Z',
    items: [
      'The Focus roster now schedules everything the platform runs on a clock, not just per-app lanes: the daily UX and Tech sweeps, the janitor, and a new fleet-improve lane (the steward’s suite-wide pick) appear as a “Platform jobs” group with the exact same controls — cadence, run-at alignment, daily window, start, and expiry — plus next-run times.',
      'So “analytics every hour, fleet improvement every 2 hours” is now two toggles and a commit. The platform side retired the sweeps’ and janitor’s standalone crons: the roster file is the single scheduler, and the seeded defaults match the old crons exactly (sweeps daily at 6 and 9 UTC, janitor every 2 hours).',
    ],
  },
  {
    v: 67,
    title: 'Full schedule control for every improve lane, right from Fleet Ops',
    kind: 'feature',
    ts: '2026-07-16T21:22:50.017Z',
    items: [
      'The Focus roster is now a real scheduler, not just on/off: each app’s lane shows its next run time and opens into a schedule editor — pick the cadence, align which hours it lands on (“the next hourly starts at 9 PM”), fence it to a daily time window, set a future start, or give it an expiry so it runs every X until Y and then stops on its own.',
      'The platform’s hourly scheduler enforces exactly the same rules (one canonical evaluator, mirrored for the in-app previews), so what the panel predicts is what the steward does. Times are shown in Central; the tick is hourly at :03 UTC — that’s the scheduling granularity.',
      'Committing still takes one click and lands on the next tick; lanes left at their defaults keep the roster file as tidy as before.',
    ],
  },
  {
    v: 66,
    title: 'One dialog system for the whole fleet',
    kind: 'polish',
    ts: '2026-07-16T03:04:06.138Z',
    items: [
      'Manager’s dialogs, confirms, and toasts now come from the shared Polecat Shell (v0.3.0) instead of app-local code — the same implementations every fleet app will use, with the same keyboard behavior everywhere: focus trapped while open, Escape closes only the topmost layer, and focus returns to whatever opened it.',
      'The shell versions picked up Manager’s best bits first: the inline “Undo” button on toasts and HTML-friendly dialog bodies are now fleet features, not Manager patches.',
      'On phones, dialogs now use the fleet’s full-screen pattern instead of a floating card — bigger targets, nothing clipped.',
      'Under the hood this deletes Manager’s entire local modal/confirm/toast implementation; the visual style is unchanged (Manager skins the shared dialogs the same way it skins the rail).',
    ],
  },
  {
    v: 65,
    title: 'The docs catch up with the platform era',
    kind: 'polish',
    ts: '2026-07-16T02:48:59.362Z',
    items: [
      'A new “Fleet Ops & the steward” documentation section explains how the fleet ships itself now — the platform steward’s branch → test → PR → merge-when-green flow, the janitor safety net, the focus roster, one-off dispatches, and how to connect a GitHub token from the vault.',
      'Swept the older sections for drift: Getting started and Activity now describe the centralized steward instead of the retired per-app hourly loop, Credentials explains the vault’s role for Fleet Ops and its at-rest encryption, the what’s-new blurb matches the slide-in panel, and Needs attention documents the new steward signals.',
    ],
  },
  {
    v: 64,
    title: 'Polecat Shell v0.2.0 — Manager’s patches graduate into the shared library',
    kind: 'polish',
    ts: '2026-07-15T22:56:44.946Z',
    items: [
      'The vendored Polecat Shell steps to v0.2.0, carrying two improvements Manager had been patching locally: keyboard-focus rings on the rail’s logo and collapse toggle, and native badge tones (the red “needs attention” count on Dashboard) — now every fleet app gets them for free.',
      'Manager’s local workarounds for both are deleted; the app now uses the shell’s native setBadge tone directly. No visible change — that’s the point.',
    ],
  },
  {
    v: 63,
    title: 'Steward problems ring the same bell as everything else',
    kind: 'feature',
    ts: '2026-07-15T22:34:09.775Z',
    items: [
      'Red steward PRs (a self-improvement change that failed its checks and got parked) and open sweep findings now count as “Needs attention” reasons — they show as chips on the dashboard callout, in the notification bell, and in the rail badge, right next to health and sync issues, and click through to the project’s Steward card for details.',
      'Same dismissal rules as every other reason: acknowledge a known finding and it stops pinging you, but a new red PR or a fresh finding changes the signature and comes back through.',
      'The signals refresh once at open, then every 5 minutes while a vault token is connected and the tab is visible — offline or rate-limited sessions simply show the local picture, never an error.',
    ],
  },
  {
    v: 62,
    title: 'Fleet Ops shows the safety nets — janitor, sweeps, and per-PR checks',
    kind: 'feature',
    ts: '2026-07-15T22:13:02.579Z',
    items: [
      'A new Fleet safety nets strip answers “is the fleet shipping itself?” at a glance: the janitor (which re-tests and merges green steward PRs every 2 hours) and the daily UX and Tech sweeps each show their last outcome, when it ran, and a link to the logs — a silently-failing safety net is now visible from Manager, not just the Actions tab.',
      'Every open steward PR in the fleet-work list (and each project’s Steward card feed) now carries a live check dot: green means the janitor will merge it on its next pass, red means it failed and was parked with a comment, pulsing means checks are still running.',
    ],
  },
  {
    v: 61,
    title: 'Fleet Ops follows steward runs live, labeled by app',
    kind: 'polish',
    ts: '2026-07-15T21:48:33.540Z',
    items: [
      'The Recent steward runs list now updates itself every 30 seconds while the panel is open — watch a dispatched run go from queued to green without touching Refresh. A small “live” indicator shows when following is active.',
      'Live-following is deliberately polite: it only polls with a vault token connected (unauthenticated GitHub rate limits are tiny), pauses while the tab is hidden, and stops entirely when you navigate away.',
      'Each run is now labeled with the app it targeted (e.g. “Steward improve — manager.polecat.live”) — the platform’s steward runs carry their target in the run title as of today, so attribution needs no log-diving.',
    ],
  },
  {
    v: 60,
    title: 'Fleet Ops — drive the platform steward from Manager',
    kind: 'feature',
    ts: '2026-07-15T21:16:26.838Z',
    items: [
      'A new Fleet Ops section turns Manager into the steward’s console: toggle each app’s hourly improve lane on the platform’s focus roster, pick a cadence, and commit the change straight from the browser — it takes effect on the next hourly tick.',
      'Dispatch one-off steward runs without leaving Manager: a focused improve run on any project (or the fleet-wide pick), plus the daily UX and Tech sweeps on demand. Recent steward runs stream in below with live status and links to the logs.',
      'Open steward work is visible at a glance: every open steward/* or shell-vendoring PR and every unresolved sweep-finding issue, across the whole fleet — and each project’s detail page gains a Steward card showing the same for just that repo.',
      'GitHub access uses a token from your Credentials vault — pick the row once and Manager reads it live (only the row’s id is stored; encrypted-and-locked values are detected and never sent). Without a token everything degrades to public read-only, and writes stay disabled.',
    ],
  },
  {
    v: 59,
    title: 'Manager moves onto the shared Polecat Shell',
    kind: 'polish',
    ts: '2026-07-15T20:21:07.419Z',
    items: [
      'The app frame — rail, top bar, theme engine and icons — now comes from the fleet’s shared, vendored Polecat Shell, the same foundation the other polecat.live apps are adopting. Manager keeps its Mission-Control look, and your saved theme, rail width and unread markers carry over untouched.',
      'New in the top bar: a 3×3 app switcher — jump to any app in the Polecat suite (Chat, JobTracker, Analytics, AutoSelector, Relay, Games) from anywhere in Manager.',
      'What’s-new opens in a slide-in panel on the right (the fleet’s standard), with the same search and feature/polish/fix filters. Each entry now shows a relative time next to its ship date.',
      'Retired the per-app What’s-new display preferences (tracked attributes and default sort) in favor of the fleet-standard feed. Everything is still searchable and filterable.',
    ],
  },
  {
    v: 58,
    title: 'Encrypt your secrets at rest on the database',
    kind: 'feature',
    ts: '2026-07-10T20:28:52.000Z',
    items: [
      'The Credentials vault can now be stored encrypted on a connected data source. Turn on “Encrypt secrets” (Admin → Data source), pick a passphrase, and Manager AES-256-GCM encrypts each credential value before it’s written to the remote — the database only ever holds ciphertext.',
      'Zero-knowledge: the passphrase is stretched into a key with PBKDF2 and never leaves your browser (it’s not stored on the server), so a leaked database dump reveals nothing without it. It’s all standard WebCrypto — no dependencies.',
      'Connect from another browser and encrypted secrets show as 🔒 locked until you enter the same passphrase once to unlock them there; the rest of the workspace loads normally. Everything non-secret stays readable as usual.',
      'Keep the passphrase safe — if you lose it, the encrypted secrets can’t be recovered. You can turn encryption back off any time to re-store them as plaintext.',
    ],
  },
  {
    v: 57,
    title: 'Data-source polish: edit a connection, clearer sync, a what’s-new legend',
    kind: 'polish',
    ts: '2026-07-09T16:57:56.000Z',
    items: [
      'You can now Edit a connected data source’s credentials in place (pre-filled), instead of only disconnecting and starting over.',
      'Replaced the confusing “Sync now” button: your changes already save to the connected database automatically, so there’s nothing to push. The manual action is now Refresh — it pulls the latest in case you edited from another browser (there’s no live subscription yet). The card now says “Changes save here automatically.”',
      'Fixed the “Connect a data source” picker showing its backend names in black on dark backgrounds (the option cards are buttons, which don’t inherit the app text colour) — readable in both themes now.',
      'Renamed the Admin button from “Connect a database” to “Connect a data source”, and fixed the wizard’s “Back” label rendering mirror-reversed (only its chevron should flip, not the text).',
      'The what’s-new timeline now has a small legend explaining every mark — the coloured dots (Feature / Polish / Fix), the Milestone flag, and the Synced tag — and each release row repeats it on hover, so a bare coloured dot is never a mystery.',
    ],
  },
  {
    v: 56,
    title: 'Connect a real database — pluggable data sources (Turso, Supabase, Firebase)',
    kind: 'feature',
    ts: '2026-07-08T21:10:36.000Z',
    items: [
      'Manager can now store its whole workspace in a real database so you reach the same data from any browser — and so the fleet can sit behind dashboards and back other Polecat apps. The rail’s new bottom chip shows where your data lives: Local · this browser, or a connected source with a live connected / syncing / error status.',
      'It’s built on one small DataSource interface — this is the first of many backends. Turso (SQLite over HTTP) works end-to-end straight from the browser; Supabase (Postgres) and Firebase (Firestore) are wired the same way. New backends are just another adapter.',
      'From Admin → Data source, connect a database and Manager inspects it: empty → it creates every object and copies your workspace up; an existing Manager workspace → it summarizes what’s there and loads it; a database in use for something else → it refuses to touch it (with a last-resort “drop everything” escape hatch). Supabase’s one-time table setup is a script it hands you to paste.',
      'Once connected it’s a write-through mirror: you keep working against a fast local copy and every change is mirrored up on a short delay. Disconnect any time to go back to local-only — your data stays put. Credentials live in this browser only.',
    ],
  },
  {
    v: 55,
    title: 'Fixed: a changelog title with a “comma, word, colon” run broke sync',
    kind: 'fix',
    ts: '2026-07-04T19:28:51.000Z',
    items: [
      'The changelog parser converts each project’s published JS module to strict JSON before importing it. Its “quote bare object keys” step ran over the whole converted string — including inside title/item text — so a title containing a run like a comma, a word, then a colon looked exactly like an unquoted key and got rewritten mid-string, injecting stray quotes and making the whole sync fail to parse.',
      'The key-quoting and trailing-comma steps now only ever touch structural text, never the inside of a string value — so any wording is safe in a title or bullet, and one odd entry can no longer take down a project’s entire sync.',
      'Also fixed the initial demo fleet’s seeded release dates, which were frozen to fixed days and slowly aged out of the "this week" / "last 7 days" views — they’re now anchored relative to first open, so a fresh workspace always reads as freshly active until you sync your own history.',
      'Added a regression check to the smoke battery covering the exact pattern.',
    ],
  },
  {
    v: 54,
    title: 'Milestones + a recommended “stable release point”',
    kind: 'feature',
    ts: '2026-07-04T19:21:10.000Z',
    items: [
      'Every project page now surfaces a Recommended release point — Manager reads the shape of the release history (a burst of features, then a stabilizing tail of polish/fixes, a quiet pause, a round version, how recent it is) and nominates the version that looks most like a complete, stable milestone, with a 0–10 confidence and the reasons why.',
      'You can mark any release as a major milestone (with an optional label like “1.0” or “Public launch”) from the 🚩 button; marked milestones get a badge everywhere the release shows.',
      'The fleet-wide Releases feed gained a Milestones filter to see just those stable points across every project.',
      'It’s all advisory — the heuristic suggests, you decide what actually gets the flag.',
    ],
  },
  {
    v: 53,
    title: 'Sweep: Docs cover health scoring, weighting & notifications; landing page catches up on its own version',
    kind: 'polish',
    ts: '2026-07-04T19:14:09.901Z',
    items: [
      'A whole feature area had zero in-app documentation until now: health scores and their five bands (Thriving → Stale), the tunable fleet-wide and per-project weighting, "Needs attention" thresholds and per-project overrides, the notification bell, and Dismiss/restore all now have a real Docs section explaining how they fit together.',
      'The library\'s doc page also now mentions the "Needs attention" saved-view chip, which existed in the app but had been missing from its own description.',
      'The public landing page\'s hero banner, activity ticker, and fleet card had drifted back to stale hand-typed version numbers (v43) even though they\'re designed to read live from this changelog — caught and corrected, and the ticker\'s baked-in fallback rows now match the real latest five entries.',
    ],
  },
  {
    v: 52,
    title: 'A "Tags" manager: rename or clean up a tag fleet-wide',
    kind: 'feature',
    ts: '2026-07-04T16:47:13.272Z',
    items: [
      'Settings → Tags now lists every tag in use across the fleet with how many projects carry it — no more hunting project-by-project to see the vocabulary you\'ve built up.',
      'Rename a tag and it updates on every project that has it in one step; renaming to a tag that already exists merges the two instead of leaving a duplicate.',
      'Remove a tag from every project at once, or click through to see exactly which projects carry it in the library. Both the rename and the fleet-wide remove are a single Undo.',
    ],
  },
  {
    v: 51,
    title: 'Public site: a "recent activity" ticker under the hero',
    kind: 'feature',
    ts: '2026-07-04T15:37:06.390Z',
    items: [
      'The landing page now shows a small scrollable strip of the last 5 real changelog entries right under the hero, so a first-time visitor gets a feel for the hourly self-improvement cadence before ever unlocking the app.',
      'It reads live from the same js/changelog.js the in-app "What\'s new" panel uses — never a hand-typed, driftable list.',
      'Drifts gently on its own, pausing the moment you hover, touch, or tab into it, and skips the auto-drift entirely under prefers-reduced-motion.',
    ],
  },
  {
    v: 50,
    title: 'Nav rail gets the app\'s own branded keyboard-focus ring',
    kind: 'polish',
    ts: '2026-07-04T14:52:44.268Z',
    items: [
      'Tabbing to the Manager logo, a section item, or the collapse/expand toggle in the left rail now shows the same cyan focus ring every other button, pill, and row in the app already carries — previously the rail was the one place still relying on the bare browser-default outline.',
      'The currently-active section keeps its usual left accent bar even while focused — the two indicators layer instead of one replacing the other.',
    ],
  },
  {
    v: 49,
    title: 'Public site: the fleet showcase feels alive — status pulse + staggered entrance',
    kind: 'feature',
    ts: '2026-07-04T14:12:55.238Z',
    items: [
      'Every project chip in the landing page\'s fleet showcase now shows a small pulsing "heartbeat" ring on its status dot for Live/Active projects — a quiet, always-on signal that the loop behind it is really running, not a static label.',
      'Each chip ticks on its own offset instead of pulsing in lockstep, so the showcase reads as several independent projects each shipping on their own clock rather than one synced blink.',
      'The chips themselves now cascade into view one after another on scroll instead of popping in all at once.',
      'Respects reduced-motion (all animation drops out, same as the rest of the landing page) and stays screen-reader-clean — the dot is decorative and hidden from assistive tech, the status text reads exactly as before.',
    ],
  },
  {
    v: 48,
    title: 'Sweep: keyboard-focus rings and a skip-to-content link, fleet-showcase status colors',
    kind: 'polish',
    ts: '2026-07-04T13:43:31.790Z',
    items: [
      'The public landing page had zero keyboard-focus styling anywhere — tabbing through it relied entirely on default browser outlines. It now gets the same branded focus ring the app already uses on every button and link, plus a "Skip to content" link that appears only when tabbed to, letting keyboard users jump straight past the nav.',
      'The app itself only had that skip-past-the-rail gap on the marketing side — added the same "Skip to content" link there too, jumping focus straight to the current view.',
      'The landing page\'s fleet showcase colored every project\'s status text the same lime green regardless of what it actually said ("Live" vs "Active") — it now uses the exact same two colors the real app\'s status pills use, so "Active" reads visibly differently from "Live" instead of looking identical.',
    ],
  },
  {
    v: 47,
    title: 'A default saved view',
    kind: 'feature',
    ts: '2026-07-04T12:54:09.594Z',
    items: [
      'One saved view can now be pinned as your default — a small pin toggle in the "Reorder saved views" modal — so it opens automatically the next time you land on Projects, instead of always resuming whatever filter you left the library on.',
      'The default chip gets a small pin badge so it\'s obvious at a glance which one is pinned; marking a new view default automatically un-pins the old one.',
      'Only applies on a fresh navigation into Projects, never mid-visit, so an active filter is never yanked out from under you while you\'re already there.',
    ],
  },
  {
    v: 46,
    title: 'Reorderable saved views',
    kind: 'feature',
    ts: '2026-07-04T12:13:24.209Z',
    items: [
      'A saved filter (Projects → "Save view") always joined the toolbar\'s chip strip at the end, forever — no way to bring the one you use daily to the front.',
      'A new "Reorder saved views" button appears once you have two or more; it opens the same drag-handle-or-up/down-arrows list Settings\' custom-field reordering already uses.',
      'Reordering is one Undo step, and the chip strip reflects the new order the moment you close the dialog.',
    ],
  },
  {
    v: 45,
    title: 'Reorderable custom fields',
    kind: 'feature',
    ts: '2026-07-04T11:34:51.734Z',
    items: [
      'Custom field definitions (Settings → Custom fields) had carried a display-order column since the typed schema shipped, but nothing let you actually change it — new fields just appended to the end forever.',
      'Every field row now has a drag handle, plus up/down arrows for keyboard and touch, to reorder the schema in one click or a drag.',
      'That order now drives where each field shows up everywhere it appears: the project detail page, the project editor, and the library toolbar\'s filter/sort dropdowns.',
      'Reordering is a single Undo step, just like every other batch edit in Manager.',
    ],
  },
  {
    v: 44,
    title: 'Number-field filters get a real range slider',
    kind: 'feature',
    ts: '2026-07-04T10:46:15.514Z',
    items: [
      'Filtering the library by a Number-type custom field (a score, a headcount, a budget) used to only do text "contains" matching — no way to ask for "between X and Y".',
      'It now shows a dual-handle range slider bounded to the real min/max already in use across the fleet, with a live readout and a one-click reset.',
      'Select-type fields still get their exact-match dropdown, and every other type still filters by "contains" — only Number changed.',
      'Saved views now remember a dialed-in range too, so a pinned filter like "budget over $500" reapplies exactly.',
    ],
  },
  {
    v: 43,
    title: "The landing page stops lying about Manager's own version",
    kind: 'polish',
    ts: '2026-07-04T10:12:05.567Z',
    items: [
      'The public site\'s hero banner and fleet showcase card for Manager were hand-typed once at launch and had been stuck on "v1" ever since, even though the real app had shipped over 40 versions.',
      'Both now read straight from the same changelog data the in-app "What\'s new" panel uses, so they can never go stale like this again — no manual edit required on future runs.',
      'Also tightened a small wording drift in the Docs page\'s description of the "Active" project status.',
      'Along the way, found and fixed a real bug in the safe changelog-sync parser: a double-quoted title containing an apostrophe (like this very entry\'s) could corrupt parsing of every field after it.',
    ],
  },
  {
    v: 42,
    title: '"Recently deleted" tray for projects',
    kind: 'feature',
    ts: '2026-07-04T07:57:39.752Z',
    items: [
      'A single Undo only ever reverses your most recent change — if you noticed a wrongly-deleted project a few actions later, the only way back was undoing everything since.',
      'Settings → Data → "Recently deleted" now lists every project removed recently (single or bulk delete), newest first, each with its own one-click Restore.',
      'Restoring a project brings its releases and credentials back with it; restoring one project out of a bulk delete leaves the rest of that batch untouched.',
    ],
  },
  {
    v: 41,
    title: '"Promote to field" for legacy custom-field values',
    kind: 'feature',
    ts: '2026-07-04T06:37:30Z',
    items: [
      'A custom-field value entered before its typed schema existed showed up in the project editor as a bare key/value pair with no way to formalize it besides recreating it by hand.',
      'That legacy row now gets a "Promote to field" button — it opens the usual add-field dialog prefilled with a guessed name and type (URL, number, date, or text) from the existing value, and carries the value over on save.',
    ],
  },
  {
    v: 40,
    title: 'Fixed: couldn’t scroll to the bottom on mobile',
    kind: 'fix',
    ts: '2026-07-04T05:07:48.872Z',
    items: [
      'On phones, the app was sized with 100vh, which counts the area behind the browser’s collapsing toolbar — so the bottom of a long list (e.g. Projects) sat under the browser chrome and couldn’t be reached.',
      'Switched the app shell to the dynamic viewport (100dvh) with a 100vh fallback, and added safe-area bottom padding so the last row clears the home indicator / gesture bar.',
      'Added a mobile smoke check that scrolls the projects list to its last row and asserts it’s actually reachable.',
    ],
  },
  {
    v: 39,
    title: 'Bulk "remove tag" in the projects library',
    kind: 'feature',
    ts: '2026-07-04T05:05:49.930Z',
    items: [
      'The library\'s bulk action bar (check rows, act on all of them at once) could add a tag across a whole selection but never remove one — now "Remove tag" sits right next to "Add tag".',
      'The picker only lists tags actually present on the checked projects, not the whole fleet\'s tag vocabulary, so there\'s nothing to mistype.',
      'One Undo reverts the whole batch, exactly like every other bulk action; a project that never had the tag is left untouched.',
    ],
  },
  {
    v: 38,
    title: 'Per-project notes, with autosave and a revision history',
    kind: 'feature',
    ts: '2026-07-04T03:46:36.762Z',
    items: [
      'Every project page now has a Notes card — a free-form Markdown scratchpad for context that doesn\'t belong in the curated assessment: why something\'s paused, what to try next, a link to a design doc.',
      'It autosaves as you pause typing, no Save button, and toggles between an Edit view and a rendered Preview.',
      'A History button lists every earlier version so you can review or restore one — a lightweight undo trail just for this text box.',
    ],
  },
  {
    v: 37,
    title: 'Manager now tracks its own real version',
    kind: 'polish',
    ts: '2026-07-04T02:22:40.853Z',
    items: [
      'The dashboard tile and project page for "Manager" (this app) used to be frozen at "v1 — Freshly launched" forever — they now reconcile against this very CHANGELOG on every load, so Manager\'s own version, release history, and health score are always the real, current numbers.',
      'Fixed a 320px overflow bug in the release timeline and the fleet-wide Releases feed: a description containing one very long unbroken word (like an env-var name) could force the whole panel wider than the screen.',
    ],
  },
  {
    v: 36,
    title: 'Releases: copy as Markdown + JSON/RSS export',
    kind: 'feature',
    ts: '2026-07-04T00:27:02.904Z',
    items: [
      'A new "Copy / Export" button on the Releases feed copies exactly what\'s on screen — your current filters and Day/Project grouping — as a pasteable Markdown list, ready for a status update or PR description.',
      'The same button downloads a JSON or RSS snapshot of every project\'s releases from the last 30 days, independent of your filters, so "what shipped across the suite" can be watched from a feed reader or script.',
    ],
  },
  {
    v: 35,
    title: 'Releases: digest mode, jump-to-date, weekly rollup',
    kind: 'feature',
    ts: '2026-07-03T23:31:03.677Z',
    items: [
      'A new "Full / Digest" toggle collapses each day or project group in the Releases feed down to a one-line summary — click it to expand back to full cards, nothing is ever hidden for good.',
      '"Jump to date" scrolls straight to any day with releases, opening its group first if it\'s collapsed.',
      'A "this week" rollup line (calendar week, not just a rolling 7 days) sums up the suite in one copyable sentence, ready to paste into a status update.',
    ],
  },
  {
    v: 34,
    title: 'Releases: group by project + "since you last looked"',
    kind: 'feature',
    ts: '2026-07-03T22:49:36.414Z',
    items: [
      'A new "By day / By project" toggle on the fleet-wide Releases feed clusters every release under its own project (most recently active first) instead of always by date.',
      'The feed now remembers when you last looked: anything shipped since then gets a quiet "new" tag and a soft accent, and the Releases rail item shows an unread count that clears the moment you open it.',
    ],
  },
  {
    v: 33,
    title: 'Releases — a fleet-wide “what shipped” timeline',
    kind: 'feature',
    ts: '2026-07-03T21:46:14.058Z',
    items: [
      'A new Releases section in the rail: every project’s releases in one timeline, newest first, grouped by day in CT — the fastest way to see what improved across the whole suite recently.',
      'Up top: summary stats (releases in the last 7 and 30 days, who shipped, the most recent release) and a per-project “who shipped” chip row for the current filter.',
      'Filter by project, kind (feature/polish/fix), and time range (7/30/90 days), or search titles and details. Click any release to jump to that project.',
    ],
  },
  {
    v: 32,
    title: 'User-defined saved views',
    kind: 'feature',
    ts: '2026-07-03T21:38:09.632Z',
    items: [
      'The projects library’s saved-view chips (All/Live/Recent/Pinned/Needs attention) are no longer a fixed set — dial in a status, sort, and field filter, then "Save view" to turn it into your own named chip.',
      'A saved chip highlights whenever its exact filter is active, and one click reapplies it later.',
      'Delete a saved view with its own × button; Undo brings it right back, same as every other change in Manager.',
    ],
  },
  {
    v: 31,
    title: 'Merge & remove, for real two-way sync',
    kind: 'feature',
    ts: '2026-07-03T20:56:59.693Z',
    items: [
      'Merge JSON can now delete rows that exist here but aren’t in the file at all — for two browsers that both add, edit, and delete. Off by default; a plain merge is still purely additive.',
      'The opt-in checkbox and its review-list tag are styled in red so the destructive direction is unmistakable before you commit.',
      'Deleting a project this way cleans up its releases, credentials, and dismissals too, just like deleting it normally does.',
      'Still one Undo for the whole merge — adds, updates, and removes together.',
    ],
  },
  {
    v: 30,
    title: 'Merge & update, not just merge & add',
    kind: 'feature',
    ts: '2026-07-03T20:03:02.604Z',
    items: [
      'Merge JSON can now refresh rows that exist in both places but drifted apart (e.g. a release edited on one machine after the backup was made on another) — opt in with a new checkbox, off by default so a plain merge is still purely additive.',
      'The review disclosure shows a field-by-field diff for every row that would update, old value → new value, before you commit to anything.',
      'Undo reverts an update-applying merge exactly like an add-only one — one click restores every changed row to what it was.',
    ],
  },
  {
    v: 29,
    title: 'Review a merge before committing it',
    kind: 'feature',
    ts: '2026-07-03T19:10:29.621Z',
    items: [
      'Merge JSON now has a "Review the N new rows" disclosure in the confirm dialog — expand it to see exactly which projects, releases, credentials, runs, and custom fields are about to land, by name, before you merge.',
      'Fixed a real mobile bug along the way: a long release title or credential key in these preview lists used to fracture into squeezed, unreadable columns on narrow phones instead of wrapping as one paragraph.',
    ],
  },
  {
    v: 28,
    title: 'Status updates itself from sync',
    kind: 'feature',
    ts: '2026-07-03T18:22:06.097Z',
    items: [
      'A project’s status now tracks its real activity every time it syncs: shipped in the last ~45 days → Live (or Active if it has no live site), gone quiet for 6+ months → Paused. In-between is left alone.',
      'Guardrails: it never overrides Archived, and each project has a Lock toggle (health panel) to pin its status so sync leaves it be. An Idea does promote once it has real releases.',
      'Turn the whole thing off in Settings → Status automation to keep statuses fully manual.',
    ],
  },
  {
    v: 27,
    title: 'Status pills now explain themselves',
    kind: 'polish',
    ts: '2026-07-03T17:54:49.612Z',
    items: [
      'Hover (or focus) any project status — Live, Active, Building, Paused, Idea, Archived — to see exactly what it means, everywhere a status shows.',
      'Clarified that status is an editorial signal you set: syncing pulls a project’s releases, it never changes the status.',
      'Manager’s own seed status is now “Live” (it’s deployed and in use), not “Building”.',
    ],
  },
  {
    v: 26,
    title: 'Scroll hints on the projects table + a dead-code sweep',
    kind: 'polish',
    ts: '2026-07-03T17:15:01.228Z',
    items: [
      'The projects library table scrolls horizontally on narrow phones (Status/Latest/Updated/Tags sit off-screen) with nothing telling you more columns exist — it now shows a soft edge fade on whichever side has more to scroll to, and the fade moves as you scroll, in both themes.',
      'Swept out CSS and JS left behind by earlier redesigns: an old "monitor log" panel style, a handful of unused classes (.chip, .crumb, .rail-foot, .token-box), and four JS helper functions nothing called anymore.',
    ],
  },
  {
    v: 25,
    title: 'Merge JSON — a non-destructive import mode',
    kind: 'feature',
    ts: '2026-07-03T16:36:06.520Z',
    items: [
      'Settings → Data has a new "Merge JSON" button alongside Import JSON: it adds rows from a backup file that don\'t already exist in this browser, and leaves everything already here untouched.',
      'A confirm dialog previews exactly what will be added — "3 new projects, 5 new releases" — before anything changes.',
      'One click on "Undo" removes everything the merge added, even when it landed rows in more than one table at once.',
      'Use this to combine a backup from one browser into another; the existing Import JSON still fully replaces your workspace when that\'s what you want.',
    ],
  },
  {
    v: 24,
    title: 'Bulk delete in the projects library',
    kind: 'feature',
    ts: '2026-07-03T15:37:08.386Z',
    items: [
      'The library\'s bulk action bar (select rows, then act on all of them at once) now has a Delete button alongside Add tag / Set status / Archive.',
      'Deleting removes every checked project — and its releases — behind an explicit "are you sure" confirm, since it\'s the one bulk action that isn\'t just a status/tag flip.',
      'One click on "Undo" restores the whole deleted batch together, same as every other bulk action.',
    ],
  },
  {
    v: 23,
    title: 'Safer workspace import',
    kind: 'feature',
    ts: '2026-07-03T14:56:36.506Z',
    items: [
      'Importing a JSON workspace (Settings → Data) now previews what\'s in the file — project, release, and credential counts — before you commit, and asks you to confirm since it replaces everything currently in this browser.',
      'Importing also clears undo history, so "Undo" can never splice old, unrelated data back into a freshly imported workspace.',
      'Garbage or non-Manager JSON is now rejected with a clear message instead of silently corrupting the workspace.',
    ],
  },
  {
    v: 22,
    title: 'Bulk actions in the projects library',
    kind: 'feature',
    ts: '2026-07-03T13:49:36.735Z',
    items: [
      'Check any number of rows in the projects library — a header checkbox selects (or clears) every currently visible one — and a bulk action bar appears with the live count.',
      'Add a tag, set a status, or archive every checked project in one shot. Each action is a single Undo: one click reverts the whole batch together, not just the last row.',
      '"Archive" is a one-click shortcut for setting status to Archived across the selection, next to the full status dropdown for anything else.',
    ],
  },
  {
    v: 21,
    title: 'Keyboard access to tiles, rows, and quick actions',
    kind: 'polish',
    ts: '2026-07-03T12:43:37.072Z',
    items: [
      'Sweep: the dashboard project tiles, quick-action cards, the "Needs attention" rows (dashboard, bell popover), and every library table row were mouse-only — clickable, but with no way to reach or activate them from a keyboard.',
      'All four are now real tab stops with a visible focus ring, and Enter/Space activates them exactly like a click — without hijacking Enter/Space on a nested button (pin, retry, dismiss, edit) that already has its own action.',
      'Grew the smoke suite with checks that tab to each one and confirm Enter navigates or activates, and that a nested button\'s own Enter doesn\'t also trigger the row underneath it.',
    ],
  },
  {
    v: 20,
    title: 'Tunable auto-sync backoff cap',
    kind: 'feature',
    ts: '2026-07-03T12:05:40.667Z',
    items: [
      'A failing project\'s auto-sync retries less often the longer it stays broken — doubling the wait each failure — but how high that backoff could climb was a fixed 8x. Settings → Auto-sync now has a "Failure backoff cap" slider (1–64x) with a one-click reset.',
      'A project\'s health panel gets a matching "Backoff cap" row next to Weighting and Attention, for a source that should back off harder (or retry sooner) than the fleet norm — same "Customize" pattern, non-destructive toggle.',
    ],
  },
  {
    v: 19,
    title: 'Per-project "needs attention" threshold override',
    kind: 'feature',
    ts: '2026-07-03T09:32:06.641Z',
    items: [
      'The health-score cutoff and auto-sync fail count behind "needs attention" were fleet-wide only — a project on a deliberately different cadence (e.g. one that should never be flagged just for being slow) had no escape hatch.',
      'A project\'s health panel now has an "Attention" row next to its weighting, with the same "Customize" pattern: its own health-score cutoff and auto-sync fail count, scoped to just that project.',
      'Turning the override off (or resetting it) falls straight back to the live fleet-wide thresholds — the dialed-in numbers stick around even while disabled.',
    ],
  },
  {
    v: 18,
    title: 'Per-project health weighting override',
    kind: 'feature',
    ts: '2026-07-03T07:58:29.160Z',
    items: [
      'Every project\'s health score used to blend the same fleet-wide weighting — no way to score a project differently even if its cadence is deliberately unusual.',
      'A project\'s health panel now has a "Customize" link next to its weighting that opens a per-project override: the same recency/velocity/status sliders as Settings → Fleet health weighting, but scoped to just that one project.',
      'Turning the override off (or resetting it) falls straight back to the live fleet-wide weighting — nothing is lost, since the dialed-in numbers stick around even while disabled.',
    ],
  },
  {
    v: 17,
    title: 'Sweep: fixed a real overflow bug + two floating-icon alignment bugs',
    kind: 'polish',
    ts: '2026-07-03T06:52:27.053Z',
    items: [
      'Credentials with a long, unbroken key name (e.g. a real env var like SOME_VERY_LONG_ENV_VARIABLE_NAME) used to push the Reveal/Copy/Edit buttons completely off-screen on a narrow phone — fixed by letting monospace text break instead of forcing the whole row wider than the viewport.',
      'On a narrow phone, the toggle switch on a Settings row (e.g. "Simple mode") and the run-mode icon in the Activity log used to float vertically centered against the middle of a wrapped, multi-line description or note instead of sitting beside its first line — both now stay pinned to the top.',
      'Grew the smoke suite with three checks that reproduce all three bugs against real content, verified to fail on the old code and pass on the fix.',
    ],
  },
  {
    v: 16,
    title: 'Tunable "Needs attention" thresholds',
    kind: 'feature',
    ts: '2026-07-03T05:12:26.963Z',
    items: [
      'Settings → "Needs attention" now lets you tune how sensitive the bell, rail badge, and dashboard callout are — a health-score cutoff and an auto-sync fail count, both drag sliders with a live "N of M projects flagged" readout.',
      'Previously these were fixed: a project only ever flagged once its health slipped to Slowing/Stale, and only after 2 auto-sync failures in a row.',
      'The per-project "Failing ×N" badge (project tile, health panel, and the Settings → Auto-sync roll-up) now uses the same tunable threshold, so a project is called "failing" consistently everywhere.',
      'One-click reset restores the shipped defaults (35 and 2) — the exact behavior this replaces.',
    ],
  },
  {
    v: 15,
    title: 'Dismiss a "Needs attention" notification',
    kind: 'feature',
    ts: '2026-07-03T03:39:22.059Z',
    items: [
      'Every row in the "Needs attention" list — on the dashboard callout and in the notification bell — now has a Dismiss action, so a problem you\'ve already seen can stop pinging you without needing to be fixed first.',
      'Dismissal is scoped to the exact reason it was raised for: if a dismissed project gets *worse* or a new problem shows up (say, its auto-sync also starts failing), it comes right back — a dismissal never hides a genuinely new issue.',
      'Nothing is thrown away — a "N dismissed" link on the dashboard callout and the bell popover opens a review list to restore any of them, and dismissing shows an instant "Undo" toast.',
      'The rail\'s Dashboard badge and the bell badge now count only active (undismissed) items; the library\'s "Needs attention" saved view is unchanged and still shows everything, dismissed or not.',
    ],
  },
  {
    v: 14,
    title: 'Rail badges Dashboard with the "Needs attention" count',
    kind: 'feature',
    ts: '2026-07-03T02:08:38.911Z',
    items: [
      'The rail\'s Dashboard item now shows the same live "Needs attention" count as the notification bell and dashboard callout, so a slipping project is visible in the nav itself — even before you land on the dashboard.',
      'With the rail collapsed to icons (the default), the count shrinks to a small dot on the Dashboard icon; opening the rail reveals the full number.',
    ],
  },
  {
    v: 13,
    title: 'Notification center',
    kind: 'feature',
    ts: '2026-07-03T01:25:25.592Z',
    items: [
      'A bell in the topbar now surfaces the same "Needs attention" signal as the dashboard callout — a live badge count and a click-through popover — from anywhere in the app, not just the dashboard.',
      'The popover lists every project whose health has slipped or whose auto-sync is failing, with a one-click "Retry now" and a jump to the project, plus an "Open dashboard" shortcut to the fuller view.',
      'Shows a calm "All clear" state when nothing needs attention, and the popover is positioned to always stay on-screen no matter how narrow the phone.',
    ],
  },
  {
    v: 12,
    title: 'Mobile sweep: three squeezed-text rows fixed at phone widths',
    kind: 'polish',
    ts: '2026-07-03T00:47:04.000Z',
    items: [
      'The "Sync all changelogs" modal used to squeeze project names down to unreadable fragments ("M..", "R..") on a narrow phone when a status chip like "10 New, 1 Updated" claimed most of the row — the status now drops to its own line under the name instead.',
      'The admin "Invites you’ve created" list and the Settings → Custom fields row both centered their action buttons against the *whole* row, so a long label wrapping to several lines made the buttons appear to float in the middle of the text — both now keep actions anchored to the top (or wrapped cleanly below) instead.',
      'The mobile no-overflow smoke check is now a loop over every rail section at 320px instead of two one-off spots, plus three new checks that pin down these exact regressions.',
    ],
  },
  {
    v: 11,
    title: '"Needs attention" rollup',
    kind: 'feature',
    ts: '2026-07-02T23:51:07.889Z',
    items: [
      'A new dashboard callout lists every project whose health has slipped to Slowing/Stale or whose auto-sync is failing — reasons, one-click "Retry now", and a jump to the project, right at the top of the fleet view.',
      'A matching "Needs attention" saved view in the projects library filters the table to the same set, so it works whichever surface you live in.',
      'Nothing renders when the fleet is healthy — this only shows up when something actually needs a look.',
    ],
  },
  {
    v: 10,
    title: 'Tunable fleet health weighting',
    kind: 'feature',
    ts: '2026-07-02T23:17:51.769Z',
    items: [
      'Settings → "Fleet health weighting" turns the three signals behind every health score — recency, release velocity, and status — into drag sliders instead of fixed constants.',
      'They\'re relative: whatever you set them to, they\'re renormalized to always add up to 100, so "50/30/20" and "5/3/2" score identically.',
      'Every score recalculates live from your weights everywhere it shows — dashboard tiles, the fleet health average, and each project\'s health panel — with one click to reset back to the shipped default (40/40/20).',
    ],
  },
  {
    v: 9,
    title: 'Auto-sync retry/backoff signal',
    kind: 'feature',
    ts: '2026-07-02T22:47:01.229Z',
    items: [
      'A project whose auto-sync keeps failing (dead site, CORS, 404) now backs off — each consecutive failure doubles the wait before retrying, capped at 8x the usual interval — instead of hammering an unreachable source forever.',
      'After 2 failures in a row it shows a "Failing ×N" badge with the reason, right in that project\'s health panel and on its dashboard tile, plus a one-click "Retry now".',
      'Settings → Auto-sync now rolls up which opted-in projects are currently failing, so nothing fails silently in the background.',
    ],
  },
  {
    v: 8,
    title: 'Fleet health score + release-velocity sparklines',
    kind: 'feature',
    ts: '2026-07-02T22:25:00.958Z',
    items: [
      'Every project now gets a 0–100 health score (Thriving / Healthy / Steady / Slowing / Stale) blending release recency, release velocity, and project status — shown as a badge on dashboard tiles and in the project detail health panel.',
      'A tiny 10-week bar sparkline next to the score shows release velocity at a glance, everywhere the score appears.',
      'A new "Fleet health" stat card on the dashboard averages every project\'s score into one at-a-glance read on the whole fleet.',
    ],
  },
  {
    v: 7,
    title: 'Mobile polish sweep',
    kind: 'polish',
    ts: '2026-07-02T22:07:02.719Z',
    items: [
      'Fixed a horizontal-scroll bug on the public landing page on small phones (390px and narrower) — the top nav and the "Enter with your token" button no longer clip off-screen.',
      'Fixed the same class of overflow on every app section (project detail, dashboard, library, credentials, docs, settings) — a header\'s action buttons now wrap onto their own row instead of running off the edge on narrow screens.',
      'Grew the smoke suite with two new checks that fail if either page regresses to a horizontal scrollbar on a narrow phone.',
    ],
  },
  {
    v: 6,
    title: 'Faster, safer auto-sync',
    kind: 'feature',
    ts: '2026-07-02T21:12:20.234Z',
    items: [
      'Auto-sync now runs on a real background loop — so a project actually re-checks on its interval while the app is open, not only when you reload.',
      'The interval can go all the way down to every 1 minute (1m / 5m / 15m / 30m / 1h / 3h / 6h / 12h / 24h).',
      'Made safe for those short intervals: a check that’s still in flight never starts another, polling pauses while the tab is hidden, and you only get a toast when something actually changed.',
    ],
  },
  {
    v: 5,
    title: 'Auto-sync & force sync',
    kind: 'feature',
    ts: '2026-07-02T20:52:45.733Z',
    items: [
      'Auto-sync quietly re-pulls an opted-in project\'s changelog on app open and on a cadence you choose — no modal, just new releases banked and a "last auto-synced" time. Turn it on fleet-wide in Settings, then opt individual projects in from their health panel.',
      'Force sync fully reconciles a project\'s releases to its source — it overwrites rows that drifted (even ones you hand-edited) and removes synced releases no longer published upstream, behind a confirm since it\'s deliberate.',
      'Both sit right next to the existing Sync button on the project page, and "Force sync all" now sits next to "Sync all" on the dashboard.',
    ],
  },
  {
    v: 4,
    title: 'Typed custom fields',
    kind: 'feature',
    ts: '2026-07-02T20:01:44.339Z',
    items: [
      'Custom project metadata is now a real, fleet-wide schema — define fields with a type (Text, Number, URL, Date, or a fixed Select list) once in Settings → Custom fields, and every project shares them.',
      'The project editor shows the right control for each field (a date picker, a dropdown of your options, etc.) instead of a bare text box, and you can define a brand-new field type without leaving the editor.',
      'Typed values render properly on the project page — URLs are clickable links, dates are formatted, and Select values show as a tag.',
      'The projects library can now filter by any custom field\'s value, and Number/Date fields join the sort dropdown alongside name, status, and version.',
    ],
  },
  {
    v: 3,
    title: 'Fleet-wide sync',
    kind: 'feature',
    ts: '2026-07-02T18:57:47.666Z',
    items: [
      'A "Sync all" quick action on the dashboard pulls every project\'s real changelog in one pass — no more clicking Sync on each project one at a time.',
      'Shows a live per-project checklist as it runs: fetching, new/updated release counts, or a clear failure reason, plus a fleet-wide summary when it\'s done.',
      'Projects with no site or changelog URL are skipped and called out, not silently ignored.',
      'The run is logged to Activity so the fleet\'s cadence log shows when a bulk sync happened.',
    ],
  },
  {
    v: 2,
    title: 'Live changelog sync',
    kind: 'feature',
    ts: '2026-07-02T17:09:57.686Z',
    items: [
      'A project’s "What’s new" timeline can now pull its real releases straight from its deployed site — a "Sync" button on the project page fetches its changelog.js, previews what’s new or changed, and imports on your say-so.',
      'Fetching never executes remote code — the changelog data is parsed as plain data, so a blocked or broken source can only fail to load, safely.',
      'Cross-origin fetches are often blocked by CORS; when that happens Manager shows a clear explanation and lets you paste the file’s contents in instead.',
      'Set a custom changelog URL per project (or let Manager guess it from the live site), and see the last-synced time on the project’s health panel.',
    ],
  },
  {
    v: 1,
    title: 'Mission Control launch',
    kind: 'feature',
    ts: '2026-07-02T00:00:00Z',
    items: [
      'A live dashboard of project tiles — status, last-updated in CT, latest version, a short assessment, and one-click links to each project’s site, its what’s-new, and the Claude Code session you drive it from.',
      'A projects library with filtering, sorting, search, pinning, and full metadata editing (add your own fields).',
      'Project detail pages with the complete what’s-new timeline, a credentials vault, in-app docs, a welcome tour, Simple mode, history + undo, and an invite-only admin gate.',
      'Dark & light themes, mobile-first layout, and a Playwright battery that gates every release.',
    ],
  },
];

export const LATEST_VERSION = CHANGELOG.reduce((m,e)=>Math.max(m,e.v),0);
